# Generated by Django 4.1.7 on 2023-03-27 05:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('blood_group', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('heart_rate', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 3, 27, 5, 46, 10, 219972, tzinfo=datetime.timezone.utc), editable=False)),
                ('modified', models.DateTimeField(default=datetime.datetime(2023, 3, 27, 5, 46, 10, 219972, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_disease', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_allergy', models.CharField(max_length=50)),
                ('reaction', models.CharField(max_length=500)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.profile')),
            ],
        ),
    ]
