# Generated by Django 4.1.7 on 2023-03-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_alter_profile_created_alter_profile_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default='0000-03-29T04:56:49.782685Z', editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='modified',
            field=models.DateTimeField(default='0000-03-29T04:56:49.782685Z'),
        ),
        migrations.DeleteModel(
            name='Allergies',
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
